title: 不远其实很遥远
description: My Personal Blog
author: 不远其实很遥远
logo: /static/img/avatar.png
github: https://github.com/calm4wei
about: 程序员

baseurl: ""
url: "https://calm4wei.github.io/"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
